config/routes.rb
require 'sidekiq/web'

Catarse::Application.routes.draw do

  devise_for :users, path: '',
    path_names:   { sign_in: :login, sign_out: :logout, sign_up: :sign_up },
    controllers:  { omniauth_callbacks: :omniauth_callbacks, passwords: :passwords }


  devise_scope :user do
    post '/sign_up', to: 'devise/registrations#create', as: :sign_up
  end


  get '/thank_you' => "static#thank_you"


  check_user_admin = lambda { |request| request.env["warden"].authenticate? and request.env['warden'].user.admin }

  filter :locale, exclude: /\/auth\//

  # Mountable engines
  constraints check_user_admin do
    mount Sidekiq::Web => '/sidekiq'
  end

  mount CatarsePaypalExpress::Engine => "/", as: :catarse_paypal_express
  mount CatarseMoip::Engine => "/", as: :catarse_moip
#  mount CatarseWepay::Engine => "/", as: :catarse_wepay

  # Channels
  constraints subdomain: /^(?!www|secure|test|local)(\w+)/ do
    namespace :channels, path: '' do
      namespace :admin do
        namespace :reports do
          resources :subscriber_reports, only: [ :index ]
        end
        resources :posts
        resources :followers, only: [ :index ]
        resources :projects, only: [ :index, :update] do
          member do
            put 'approve'
            put 'reject'
            put 'push_to_draft'
            put 'push_to_trash'
          end
        end
      end

      resources :posts
      get '/', to: 'profiles#show', as: :profile
      get '/how-it-works', to: 'profiles#how_it_works', as: :about
      resource :profile
      resources :projects, only: [:new, :create, :show] do
        collection do
          get 'video'
        end
      end
      # NOTE We use index instead of create to subscribe comming back from auth via GET
      resource :channels_subscriber, only: [:show, :destroy], as: :subscriber
    end
  end

  # Root path should be after channel constraints
  root to: 'projects#index'

  get "/explore" => "explore#index", as: :explore

  namespace :reports do
    resources :contribution_reports_for_project_owners, only: [:index]
  end

  resources :projects, only: [:index, :create, :update, :new, :show] do
    resources :updates, controller: 'projects/updates', only: [ :index, :create, :destroy ]
    resources :rewards, only: [ :index, :create, :update, :destroy, :new, :edit ] do
      member do
        post 'sort'
      end
    end
    resources :contributions, controller: 'projects/contributions' do
      member do
        put 'credits_checkout'
      end
    end
    collection do
      get 'video'
    end
    member do
      put 'pay'
      get 'embed'
      get 'video_embed'
      get 'embed_panel'
      get 'send_to_analysis'
    end
  end
  resources :users do
    resources :projects, controller: 'users/projects', only: [ :index ]
    member do
      get :unsubscribe_notifications
      get :credits
    end
    collection do
      get :uservoice_gadget
    end
    resources :contributions, controller: 'users/contributions', only: [:index] do
      member do
        get :request_refund
      end
    end

    resources :unsubscribes, only: [:create]
    member do
      get 'projects'
      put 'unsubscribe_update'
      put 'update_email'
      put 'update_password'
    end
  end

  namespace :admin do
    resources :projects, only: [ :index, :update, :destroy ] do
      member do
        put 'approve'
        put 'reject'
        put 'push_to_draft'
        put 'push_to_trash'
      end
    end

    resources :statistics, only: [ :index ]
    resources :financials, only: [ :index ]

    resources :contributions, only: [ :index, :update, :show ] do
      member do
        put 'confirm'
        put 'pendent'
        put 'change_reward'
        put 'refund'
        put 'hide'
        put 'cancel'
        put 'push_to_trash'
      end
    end
    resources :users, only: [ :index ]

    namespace :reports do
      resources :contribution_reports, only: [ :index ]
    end
  end

  get "/:permalink" => "projects#show", as: :project_by_slug
end

app/models/channel.rb
class Channel < ActiveRecord::Base
  extend CatarseAutoHtml

  include Shared::VideoHandler

  attr_accessible :description, :name, :permalink, :video_url, :video_embed_url, :twitter, :facebook, :website, :image, :how_it_works
  schema_associations

  validates_presence_of :name, :description, :permalink
  validates_uniqueness_of :permalink

  has_and_belongs_to_many :projects, -> { order("online_date desc") }
  has_and_belongs_to_many :subscribers, class_name: 'User', join_table: :channels_subscribers
  has_many :subscriber_reports

  catarse_auto_html_for field: :how_it_works, video_width: 560, video_height: 340

  delegate :display_facebook, :display_twitter, :display_website, to: :decorator
  mount_uploader :image, ProfileUploader

  scope :by_permalink, ->(p) { where("lower(channels.permalink) = lower(?)", p) }

  def self.find_by_permalink!(string)
    self.by_permalink(string).first!
  end

  def has_subscriber? user
    user && subscribers.where(id: user.id).first.present?
  end

  def to_s
    self.name
  end

  # Links to channels should be their permalink
  def to_param; self.permalink end

  # Using decorators
  def decorator
    @decorator ||= ChannelDecorator.new(self)
  end
end

app/controllers/channels/admin/followers_controller.rb
class Channels::Admin::FollowersController < Admin::BaseController
  layout 'catarse_bootstrap'
  add_to_menu "channels.admin.followers_menu", :channels_admin_followers_path
  actions :index

  before_filter do
    @channel = Channel.find_by_permalink!(request.subdomain.to_s)
  end

  def index
    @total_subscribers = @channel.subscribers.count
    @subscribers = channel.subscribers.page(params[:page])
  end
end

app/controllers/channels/admin/posts_controller.rb
class Channels::Admin::PostsController < Admin::BaseController
  layout 'catarse_bootstrap'
  add_to_menu 'channels.admin.posts_menu', :channels_admin_posts_path
  load_and_authorize_resource :channel_posts
  inherit_resources
  defaults resource_class: ChannelPost

  def edit
    return redirect_to channels_admin_posts_path if resource.visible
  end

  def update
    if params[:channel_post][:visible]
      update!(notice: I18n.t('channels.admin.posts.update.published_message'))
    else
      update!
    end
  end

  def begin_of_association_chain
    channel
  end

  def collection
    @posts ||= apply_scopes(end_of_association_chain.ordered.page(params[:page]))
  end

  protected

  def create_resource(object)
    object.user_id = current_user.id
    super
  end
end

app/controllers/channels/admin/projects_controller.rb
class Channels::Admin::ProjectsController < Admin::BaseController
  layout 'catarse_bootstrap'
  has_scope :by_id, :pg_search, :user_name_contains, :order_by, :with_state
  has_scope :between_created_at, using: [ :start_at, :ends_at ], allow_blank: true

  before_filter do
    @total_projects =  channel.projects.size
  end

  [:approve, :reject, :push_to_draft, :push_to_trash].each do |name|
    define_method name do
      @project    = channel.projects.find(params[:id])
      @project.send("#{name.to_s}!")
      redirect_to :back
    end
  end

  protected
  def begin_of_association_chain
    channel
  end

  def collection
    @projects = apply_scopes(channel.projects.page(params[:page]))
  end
end

app/controllers/channels/admin/reports/subscriber_reports_controller.rb
class Channels::Admin::Reports::SubscriberReportsController < Admin::Reports::BaseController
  private
  def end_of_association_chain
    SubscriberReport.where(channel_id: channel.id)
  end
end

app/controllers/channels/base_controller.rb
class Channels::BaseController < ApplicationController
  skip_before_filter :set_locale
  before_filter do
    I18n.locale = 'pt'
  end
end

app/controllers/channels/channels_subscribers_controller.rb
class Channels::ChannelsSubscribersController < Channels::BaseController
  inherit_resources
  after_filter :verify_authorized, except: [:create]
  actions :show, :destroy, :create

  # We use show as create to redirect to this action after auth
  def show
    @channels_subscriber = ChannelsSubscriber.new subscription_attributes
    authorize @channels_subscriber
    create! do |format|
      flash[:notice] = I18n.t('channels_subscribers.created', channel: channel.name)
      return redirect_to root_path
    end
  # This is needed when you press the follow channel button without being signed in
  rescue
    return redirect_to sign_up_path
  end

  def destroy
    authorize resource
    destroy! do |format|
      flash[:notice] = I18n.t('channels_subscribers.deleted', channel: channel.name)
      return redirect_to root_path
    end
  end

  def resource
    @channels_subscriber ||= ChannelsSubscriber.where(subscription_attributes).first!
  end

  private
  def subscription_attributes
    { channel_id: channel.id, user_id: current_user.try(:id) }
  end
end

app/controllers/channels/posts_controller.rb
class Channels::PostsController < Channels::BaseController
  layout 'catarse_bootstrap'
  inherit_resources

  private

  def begin_of_association_chain
    channel
  end

  def end_of_association_chain
    begin_of_association_chain.posts.ordered.visible
  end
end

app/controllers/channels/profiles_controller.rb
class Channels::ProfilesController < Channels::BaseController
  layout 'catarse_bootstrap'
  add_to_menu 'channels.admin.profile_menu', :edit_channels_profile_path
  inherit_resources
  actions :show, :edit, :update
  custom_actions resource: [:how_it_works]
  after_filter :verify_authorized, except: [:how_it_works, :show]

  def edit
    authorize resource
    edit!
  end

  def update
    authorize resource
    update!
  end

  def resource
    @profile ||= channel
  end
end

app/controllers/channels/projects_controller.rb
class Channels::ProjectsController < ProjectsController
  layout 'catarse_bootstrap'
  belongs_to :channel, finder: :find_by_permalink!, param: :profile_id


  # Inheriting from the original Projects controller
  # With one addition: we include the project into the current channel
  before_filter only: [:create] { params[:project][:channels] = [channel] }

  prepend_before_filter{ params[:profile_id] = request.subdomain }
end

app/views/catarse_bootstrap/channels/posts/index.html.slim
= render 'shared/header_channel'
= content_for :title, channel.name

section.line-box
  .row
    .large-12.columns
      .presentation
        h1.channel-title
          = t('channels.posts.title')
          | : 
          = link_to channel.name, root_path, class: 'standard-link'
        .row
          .large-4.columns
            .channel-followers-wrapper
              - if channel.has_subscriber?(current_user)
                .large-6.columns.no-padding
                  = link_to channels_subscriber_path, {method: :delete, class: [:button, :medium, :negative]} do
                    .stop_following= t('channels.unfollow')
              - else
                .large-6.columns.no-padding
                  = link_to t('channels.follow'), channels_subscriber_path, class: [:button, :medium, :negative], title: t('channels.follow')
              .large-6.columns
                .channel-followers[title=t('channels.subscribed', count: channel.channels_subscribers.size)]
                  = t('channels.subscribed', count: channel.channels_subscribers.size)



article.row.channel-posts-wrapper
  - collection.each do |resource|
    section.large-9.columns.channel-post
      h3.channel-post-title= link_to resource.title, channels_post_path(resource), class: 'standard-link-one'
      p= l(resource.created_at, format: :updates)
      == resource.body_html
      .row
        .large-1.columns
          .twitter_share= render_twitter text: "#{resource.title}", url: channels_post_url(resource, locale: I18n.locale)
        .large-6.columns.left
          .facebook_share= render_facebook_like href: channels_post_url(resource, locale: I18n.locale), width: '360'
    .large-3.columns
.clearfix
= render 'shared/footer_channel'

app/views/catarse_bootstrap/channels/posts/show.html.slim
= render 'shared/header_channel'
= content_for :title, channel.name
= content_for :meta_tags do
  meta property="og:title"        content=resource.title
  meta property="og:type"         content=:cause
  meta property="og:url"          content=url_for(only_path: false)
  meta property="og:image"        content=channel.image.curator_thumb.url
  meta property="og:site_name"    content=channel.name
  meta property="fb:app_id"       content=Configuration[:facebook_app_id]
  meta property="og:description"  content=channel.description


article.row.channel-posts-wrapper
  br/
  br/
  .large-9.columns
    = link_to '← Voltar para as novidades', channels_posts_path, class: 'navigation-link'
    br/
    br/
  section.large-9.columns
    h1.channel-post-title
      = resource.title
    p= l(resource.created_at, format: :updates)
    == resource.body_html
    br/
    br/
    .row
      .large-1.columns
        .twitter_share= render_twitter text: "#{resource.title}", url: channels_post_url(resource, locale: I18n.locale)
      .large-6.columns.left
        .facebook_share= render_facebook_like href: channels_post_url(resource, locale: I18n.locale), width: '360'
    .large-3.columns
  .large-3.columns

br/

/article.row.channel-posts-comments-wrapper
  section.large-9.columns.channel-posts-comments
    #channel_posts_comments

= render 'shared/footer_channel'